name: Disparar Action em Outro Repositório
on:
  push:
    branches:
      - main

jobs:
  disparar-action:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar Action em Outro Repositório
        uses: actions/checkout@v2
      - name: Disparar Action em Outro Repositório
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/PedroPGuimaraes/update_image_base/actions/workflows/7209223471/dispatches \
          -d '{"ref":"main"}'